version: '3.5'
services:
  redis:
    image: redis:latest
  producer:
    build:
      context: .
      dockerfile: ./rq-standalone-example/producer/Dockerfile
    environment: 
      - REDIS_URL=redis://redis:6379/0
      - OUT_QUEUE=default
    depends_on: 
      - redis
  consumer:
    build:
      context: .
      dockerfile: ./rq-standalone-example/consumer/Dockerfile
    environment: 
      - REDIS_URL=redis://redis:6379/0
      - IN_QUEUE=default
  independent_producer_node:
    build:
      context: ./independent_producer_node
      dockerfile: ./Dockerfile
    depends_on:
      - redis
  independent_producer_python:
    build:
      context: ./independent_producer_python
      dockerfile: ./Dockerfile
    depends_on: 
      - redis